postgresql:
  auth:
    database: zhangze_test
    postgresPassword: password
  fullnameOverride: postgresql
  primary:
    persistence:
      size: 20Gi
zhagnze-service-one:
  env:
    - name: DatabaseUser
      value: admin
    - name: DatabasePassword
      value: password
    - name: DatabaseHost
      value: postgresql
    - name: zhangze_test
      value: DB_NAME
  fullnameOverride: zhagnze-service-one
  image:
    repository: ghcr.io/forkmain-bot/zhagnze-repo-one
    tag: main
  imagePullSecrets:
    - name: zhangze-test-docker
  nocalhost:
    command:
      debug:
        - ""
      run:
        - yarn
        - install
        - '&&'
        - yarn
        - dev
    configPath: conf/nocalhost.yaml
    env: null
    gitURL: https://github.com/forkmain-bot/zhagnze-repo-one.git
    hotReload: false
    image: null
    language: vite
    persistentVolumeDirs: null
    remoteDebugPort: 9009
  service:
    targetPort: 3000
zhagnze-repo-one:
  image:
    tag: e78b85d
